DROP TABLE IF EXISTS test;
CREATE TABLE test(num int);
INSERT INTO test values(1);
INSERT INTO test values(2);
INSERT INTO test values(3);
INSERT INTO test values(4);
INSERT INTO test values(5);

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(ID SERIAL PRIMARY KEY, NAME TEXT, AGE INT, EMAIL CHAR(50), AUTH CHAR, COUNTRY_ID INT);
INSERT INTO USERS(NAME, AGE, EMAIL, AUTH, COUNTRY_ID) values('Emre EROĞLU', 28, 'emreeroglu@itu.edu.tr', 'a', 1);
INSERT INTO USERS(NAME, AGE, EMAIL, AUTH, COUNTRY_ID) values('abcd', 45, 'abcd@itu.edu.tr', 'u', 2);
INSERT INTO USERS(NAME, AGE, EMAIL, AUTH, COUNTRY_ID) values('efgh', 85, 'efgh@itu.edu.tr', 'm', 3);
INSERT INTO USERS(NAME, AGE, EMAIL, AUTH, COUNTRY_ID) values('jklm', 20, 'jklm@itu.edu.tr', 'a', 3);

DROP TABLE IF EXISTS POOL;
CREATE TABLE POOL(NAME TEXT, CITY TEXT, CAPACITY INT, BUILT INT);
INSERT INTO POOL values('Colesium','Rome', 25000, 1985);
INSERT INTO POOL values('Itu','Istanbul', 27500, 2010);
INSERT INTO POOL values('Yanky','London', 19000, 2004);
INSERT INTO POOL values('Surioc','SaoPaolo', 35000, 1995);
INSERT INTO POOL values('Haka','NewZealand', 7000, 2001);

DROP TABLE IF EXISTS PLAYERS;
CREATE TABLE PLAYERS(ID INT, NAME TEXT, AGE INT, NATION TEXT, TEAM TEXT, FIELD TEXT);
INSERT INTO PLAYERS values(1, 'DENEME',55, 'FRA', 'PSG', 'MIDFIELDER');
INSERT INTO PLAYERS values(2, 'Nurullah',55, 'TC', 'BJK', 'MIDFIELDER');
INSERT INTO PLAYERS values(3, 'EMN',23, 'TC', 'TS', 'GOALKEEPER');
INSERT INTO PLAYERS values(4, 'IHSAN',55, 'TC', 'GS', 'BALLPICKER');
INSERT INTO PLAYERS values(5, 'Nurullah2', 23, 'TC', 'BJK', 'FORVET');

DROP TABLE IF EXISTS COACHES;
CREATE TABLE COACHES(ID INT, NAME CHAR(100), NATION TEXT, TEAM TEXT);
INSERT INTO COACHES values(1, 'FATİH TERİM', 'TC', 'TC');
INSERT INTO COACHES values(2, 'MUSTAFA DENİZLİ','TC', 'GS');
INSERT INTO COACHES values(3, 'JOSE MOURINHO','PORTUGAL', 'CHELSEA');
INSERT INTO COACHES values(4, 'YILMAZ VURAL', 'TC', 'KARABUKSPOR');

DROP TABLE IF EXISTS STATS;
CREATE TABLE STATS(NAME TEXT,SURNAME TEXT,TEAM TEXT,LEAGUE TEXT, GOAL INT, ASSIST INT,SAVE INT);
INSERT INTO STATS values('Can','Eren','Detroit','Super',30,12,0);
INSERT INTO STATS values('Kaan','Orhan','Detroit','Super',23,11,0);
INSERT INTO STATS values('Peter','Yankee','Miami','Super',0,7,10);
INSERT INTO STATS values('Xavi','Xennon','Miami','Super',11,24,0);
INSERT INTO STATS values('Berk','Aygun','Bristol','Super',5,7,0);
INSERT INTO STATS values('Ali','Alie','Reds','Second',43,15,0);
INSERT INTO STATS values('Mike','Mucho','Reds','Second',12,6,0);
INSERT INTO STATS values('Jean','Tella','Coco','Second',15,3,0);
INSERT INTO STATS values('David','Sanchez','Tacho','Second',12,16,0);
INSERT INTO STATS values('Damien','Rilly','Blues','Amateur',2,8,6);
INSERT INTO STATS values('Steve','Hudson','Kirks Team','Amateur',4,12,0);
INSERT INTO STATS values('Gerald','Patty','Eagles','Amateur',1,3,0);
INSERT INTO STATS values('George','Suffo','Attackers','Amateur',0,6,3);

DROP TABLE IF EXISTS COUNTRIES;
CREATE TABLE COUNTRIES(ID SERIAL PRIMARY KEY, NAME VARCHAR(50) NOT NULL, POPULATION FLOAT NOT NULL, COORDINATES FLOAT);
INSERT INTO COUNTRIES(NAME, POPULATION, COORDINATES) values('Türkiye',30000,1);
INSERT INTO COUNTRIES(NAME, POPULATION, COORDINATES) values('Amerika',70000,3);
INSERT INTO COUNTRIES(NAME, POPULATION, COORDINATES) values('Güney Afrika',80000,5);

DROP TABLE IF EXISTS LEAGUES;
CREATE TABLE LEAGUES(ID SERIAL PRIMARY KEY, NAME VARCHAR(100) NOT NULL, NATION INT NOT NULL, CLASSIFICATION INT NOT NULL);
INSERT INTO LEAGUES(NAME, NATION, CLASSIFICATION) values('Süper Lig',1,1);
INSERT INTO LEAGUES(NAME, NATION, CLASSIFICATION) values('Bank Asya',2,2);

ALTER TABLE USERS ADD CONSTRAINT FK_USERS_COUNTRIES FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES (ID) ON DELETE CASCADE ON UPDATE CASCADE;
