DROP TABLE IF EXISTS test;
CREATE TABLE test(num int);
INSERT INTO test values(1);
INSERT INTO test values(2);
INSERT INTO test values(3);
INSERT INTO test values(4);
INSERT INTO test values(5);

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(ID SERIAL PRIMARY KEY, NAME TEXT, AGE INT, EMAIL CHAR(50), AUTH CHAR, COUNTRY_ID INT);
INSERT INTO USERS(NAME, AGE, EMAIL, AUTH, COUNTRY_ID) values('Emre EROĞLU', 28, 'emreeroglu@itu.edu.tr', 'a', 1);
INSERT INTO USERS(NAME, AGE, EMAIL, AUTH, COUNTRY_ID) values('abcd', 45, 'abcd@itu.edu.tr', 'u', 2);
INSERT INTO USERS(NAME, AGE, EMAIL, AUTH, COUNTRY_ID) values('efgh', 85, 'efgh@itu.edu.tr', 'm', 3);
INSERT INTO USERS(NAME, AGE, EMAIL, AUTH, COUNTRY_ID) values('jklm', 20, 'jklm@itu.edu.tr', 'a', 3);

DROP TABLE IF EXISTS POOL;
CREATE TABLE POOL(NAME TEXT, CITY TEXT, CAPACITY INT, BUILT INT);
INSERT INTO POOL values('Colesium','Rome', 25000, 1985);
INSERT INTO POOL values('Itu','Istanbul', 27500, 2010);
INSERT INTO POOL values('Yanky','London', 19000, 2004);
INSERT INTO POOL values('Surioc','SaoPaolo', 35000, 1995);
INSERT INTO POOL values('Haka','NewZealand', 7000, 2001);

DROP TABLE IF EXISTS PLAYERS;
CREATE TABLE PLAYERS(ID SERIAL PRIMARY KEY, NAME TEXT, SURNAME TEXT, AGE INT, NATION INT, TEAM TEXT, FIELD TEXT, GOAL INT);
INSERT INTO PLAYERS(NAME, SURNAME, AGE, NATION, TEAM, FIELD, GOAL) values('Adam',  'Wright',  38,  2, 'UCLA',         'Attacker',   9);
INSERT INTO PLAYERS(NAME, SURNAME, AGE, NATION, TEAM, FIELD, GOAL) values('Louis', 'Handley', 39,  2, 'California',   'Defence',    3);
INSERT INTO PLAYERS(NAME, SURNAME, AGE, NATION, TEAM, FIELD, GOAL) values('Ryan',  'Bailey',  40,  2, 'Vk Partizan',  'Attacker',   10);
INSERT INTO PLAYERS(NAME, SURNAME, AGE, NATION, TEAM, FIELD, GOAL) values('IHSAN', 'Halici',  55,  3, 'GS',           'BALLPICKER', 11);
INSERT INTO PLAYERS(NAME, SURNAME, AGE, NATION, TEAM, FIELD, GOAL) values('Emre',  'Eroglu',  48,  1, 'BJK',          'FORVET',     9);

DROP TABLE IF EXISTS COACHES;
CREATE TABLE COACHES(ID SERIAL PRIMARY KEY, NAME TEXT, SURNAME TEXT, NATION INT, TEAM TEXT);
INSERT INTO COACHES(NAME, SURNAME, NATION, TEAM) values('Matt',   'Biondi',  2,  'California');
INSERT INTO COACHES(NAME, SURNAME, NATION, TEAM) values('Sinan',  'Turunç',  1,  'TC');
INSERT INTO COACHES(NAME, SURNAME, NATION, TEAM) values('Ihsan',  'Halici',  3,  'ZonguldakSpor');
INSERT INTO COACHES(NAME, SURNAME, NATION, TEAM) values('YILMAZ', 'VURAL',   3,  'KARABUKSPOR');

DROP TABLE IF EXISTS STATS;
CREATE TABLE STATS(NAME TEXT,SURNAME TEXT,TEAM TEXT,LEAGUE TEXT, GOAL INT, ASSIST INT,SAVE INT);
INSERT INTO STATS values('Can','Eren','Detroit','Super',30,12,0);
INSERT INTO STATS values('Kaan','Orhan','Detroit','Super',23,11,0);
INSERT INTO STATS values('Peter','Yankee','Miami','Super',0,7,10);
INSERT INTO STATS values('Xavi','Xennon','Miami','Super',11,24,0);
INSERT INTO STATS values('Berk','Aygun','Bristol','Super',5,7,0);
INSERT INTO STATS values('Ali','Alie','Reds','Second',43,15,0);
INSERT INTO STATS values('Mike','Mucho','Reds','Second',12,6,0);
INSERT INTO STATS values('Jean','Tella','Coco','Second',15,3,0);
INSERT INTO STATS values('David','Sanchez','Tacho','Second',12,16,0);
INSERT INTO STATS values('Damien','Rilly','Blues','Amateur',2,8,6);
INSERT INTO STATS values('Steve','Hudson','Kirks Team','Amateur',4,12,0);
INSERT INTO STATS values('Gerald','Patty','Eagles','Amateur',1,3,0);
INSERT INTO STATS values('George','Suffo','Attackers','Amateur',0,6,3);

DROP TABLE IF EXISTS COUNTRIES;
CREATE TABLE COUNTRIES(ID SERIAL PRIMARY KEY, NAME VARCHAR(50) NOT NULL, POPULATION FLOAT NOT NULL, COORDINATES FLOAT);
INSERT INTO COUNTRIES(NAME, POPULATION, COORDINATES) values('Türkiye',30000,1);
INSERT INTO COUNTRIES(NAME, POPULATION, COORDINATES) values('Amerika',70000,3);
INSERT INTO COUNTRIES(NAME, POPULATION, COORDINATES) values('Güney Afrika',80000,5);

DROP TABLE IF EXISTS LEAGUES;
CREATE TABLE LEAGUES(ID SERIAL PRIMARY KEY, NAME VARCHAR(100) NOT NULL, NATION INT NOT NULL, CLASSIFICATION INT NOT NULL);
INSERT INTO LEAGUES(NAME, NATION, CLASSIFICATION) values('Süper Lig',1,1);
INSERT INTO LEAGUES(NAME, NATION, CLASSIFICATION) values('Bank Asya',2,2);

DROP TABLE IF EXISTS MESSAGES;
CREATE TABLE MESSAGES(ID SERIAL PRIMARY KEY, TITLE VARCHAR(100) NOT NULL, PHONE BIGINT, MAIL VARCHAR(100), MESSAGE TEXT NOT NULL);
INSERT INTO MESSAGES(TITLE, PHONE, MAIL, MESSAGE) values('Baslik',05553337766,'emn@gmail.com','selam gençlik');

ALTER TABLE USERS ADD CONSTRAINT FK_USERS_COUNTRIES FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES (ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PLAYERS ADD CONSTRAINT FK_PLAYERS_COUNTRIES FOREIGN KEY (NATION) REFERENCES COUNTRIES (ID) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE COACHES ADD CONSTRAINT FK_COACHES_COUNTRIES FOREIGN KEY (NATION) REFERENCES COUNTRIES (ID) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE LEAGUES ADD CONSTRAINT FK_LEAGUES_COUNTRIES FOREIGN KEY (NATION) REFERENCES COUNTRIES (ID) ON DELETE CASCADE ON UPDATE CASCADE;
